name: Run Python Tests

on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - "test/**"

jobs:
  test:
    runs-on: ubuntu-20.04  # Ensures Python 3.6 is available

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]  # Installs `pytest` and `setuptools` from `extras_require`

      - name: Run tests with pytest
        run: pytest test/
